title: Lochana Perera
description: my pursuit to understand the world
theme: just-the-docs

url: https://fivetwentythree.github.io/

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

#color_scheme: dark

# Social card settings
social_image: /assets/images/social_card.png # Default social card image

