title: Lochana Perera
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://fivetwentythree.github.io/

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
